CREATE TABLE IF NOT EXISTS master_books (
  id INTEGER PRIMARY KEY,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  lccn TEXT DEFAULT NULL,
  isbn TEXT DEFAULT NULL,
  title TEXT DEFAULT NULL,
  author TEXT DEFAULT NULL,
  copyright_date DATE DEFAULT NULL
  publisher TEXT DEFAULT NULL,
  location TEXT DEFAULT NULL,
  genre TEXT DEFAULT NULL,
  pages TEXT DEFAULT NULL,
)
