CREATE TABLE IF NOT EXISTS master_books (
  id INTEGER PRIMARY KEY,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  lccn TEXT DEFAULT NULL,
  isbn TEXT DEFAULT NULL,
  title TEXT DEFAULT NULL,
  author TEXT DEFAULT NULL,
  publish_date DATE DEFAULT NULL
)
